# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/160ACB750ACB5083/Git_Repo/3D_福彩/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1160, 669)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 1161, 671))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftFrame = QtWidgets.QFrame(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftFrame.sizePolicy().hasHeightForWidth())
        self.leftFrame.setSizePolicy(sizePolicy)
        self.leftFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftFrame.setObjectName("leftFrame")
        self.menuList = QtWidgets.QListWidget(self.leftFrame)
        self.menuList.setGeometry(QtCore.QRect(30, 40, 281, 581))
        self.menuList.setStyleSheet("")
        self.menuList.setObjectName("menuList")
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        self.horizontalLayout.addWidget(self.leftFrame)
        self.line = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.rightFrame = QtWidgets.QFrame(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightFrame.sizePolicy().hasHeightForWidth())
        self.rightFrame.setSizePolicy(sizePolicy)
        self.rightFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightFrame.setObjectName("rightFrame")
        self.stackedWidget = QtWidgets.QStackedWidget(self.rightFrame)
        self.stackedWidget.setGeometry(QtCore.QRect(19, -21, 771, 671))
        self.stackedWidget.setObjectName("stackedWidget")
        self.allDataPage = QtWidgets.QWidget()
        self.allDataPage.setObjectName("allDataPage")
        self.allDataTable = QtWidgets.QTableWidget(self.allDataPage)
        self.allDataTable.setGeometry(QtCore.QRect(5, 61, 751, 521))
        self.allDataTable.setObjectName("allDataTable")
        self.allDataTable.setColumnCount(0)
        self.allDataTable.setRowCount(0)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.allDataPage)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(220, 610, 351, 34))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.updateData = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.updateData.setObjectName("updateData")
        self.horizontalLayout_2.addWidget(self.updateData)
        self.exportAllData = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.exportAllData.setObjectName("exportAllData")
        self.horizontalLayout_2.addWidget(self.exportAllData)
        self.stackedWidget.addWidget(self.allDataPage)
        self.perNumberCountPage = QtWidgets.QWidget()
        self.perNumberCountPage.setObjectName("perNumberCountPage")
        self.perNumberCountTable = QtWidgets.QTableWidget(self.perNumberCountPage)
        self.perNumberCountTable.setGeometry(QtCore.QRect(5, 61, 751, 531))
        self.perNumberCountTable.setObjectName("perNumberCountTable")
        self.perNumberCountTable.setColumnCount(0)
        self.perNumberCountTable.setRowCount(0)
        self.perNumberCountTable.horizontalHeader().setDefaultSectionSize(125)
        self.exportPerNumberCount = QtWidgets.QPushButton(self.perNumberCountPage)
        self.exportPerNumberCount.setGeometry(QtCore.QRect(310, 610, 141, 32))
        self.exportPerNumberCount.setObjectName("exportPerNumberCount")
        self.stackedWidget.addWidget(self.perNumberCountPage)
        self.countStatisticsPage = QtWidgets.QWidget()
        self.countStatisticsPage.setObjectName("countStatisticsPage")
        self.tabWidget_8 = QtWidgets.QTabWidget(self.countStatisticsPage)
        self.tabWidget_8.setGeometry(QtCore.QRect(0, 40, 771, 601))
        self.tabWidget_8.setObjectName("tabWidget_8")
        self.countStatisticsTableTab = QtWidgets.QWidget()
        self.countStatisticsTableTab.setObjectName("countStatisticsTableTab")
        self.countStatisticsTable = QtWidgets.QTableWidget(self.countStatisticsTableTab)
        self.countStatisticsTable.setGeometry(QtCore.QRect(-1, -1, 771, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countStatisticsTable.sizePolicy().hasHeightForWidth())
        self.countStatisticsTable.setSizePolicy(sizePolicy)
        self.countStatisticsTable.setObjectName("countStatisticsTable")
        self.countStatisticsTable.setColumnCount(0)
        self.countStatisticsTable.setRowCount(0)
        self.exportCountStatistics = QtWidgets.QPushButton(self.countStatisticsTableTab)
        self.exportCountStatistics.setGeometry(QtCore.QRect(310, 520, 161, 32))
        self.exportCountStatistics.setObjectName("exportCountStatistics")
        self.tabWidget_8.addTab(self.countStatisticsTableTab, "")
        self.countStatisticsBarChartTab = QtWidgets.QWidget()
        self.countStatisticsBarChartTab.setObjectName("countStatisticsBarChartTab")
        self.horizontalLayoutWidget_19 = QtWidgets.QWidget(self.countStatisticsBarChartTab)
        self.horizontalLayoutWidget_19.setGeometry(QtCore.QRect(280, 480, 221, 51))
        self.horizontalLayoutWidget_19.setObjectName("horizontalLayoutWidget_19")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_19)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_33 = QtWidgets.QLabel(self.horizontalLayoutWidget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_19.addWidget(self.label_33)
        self.countStatisticsBarChartLimit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countStatisticsBarChartLimit.sizePolicy().hasHeightForWidth())
        self.countStatisticsBarChartLimit.setSizePolicy(sizePolicy)
        self.countStatisticsBarChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.countStatisticsBarChartLimit.setObjectName("countStatisticsBarChartLimit")
        self.horizontalLayout_19.addWidget(self.countStatisticsBarChartLimit)
        self.label_34 = QtWidgets.QLabel(self.horizontalLayoutWidget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_19.addWidget(self.label_34)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem)
        self.repaintCountStatisticsBarChartButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_19)
        self.repaintCountStatisticsBarChartButton.setObjectName("repaintCountStatisticsBarChartButton")
        self.horizontalLayout_19.addWidget(self.repaintCountStatisticsBarChartButton)
        self.tabWidget_8.addTab(self.countStatisticsBarChartTab, "")
        self.countStatisticsPieChartTab = QtWidgets.QWidget()
        self.countStatisticsPieChartTab.setObjectName("countStatisticsPieChartTab")
        self.horizontalLayoutWidget_20 = QtWidgets.QWidget(self.countStatisticsPieChartTab)
        self.horizontalLayoutWidget_20.setGeometry(QtCore.QRect(270, 480, 221, 51))
        self.horizontalLayoutWidget_20.setObjectName("horizontalLayoutWidget_20")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_20)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_35 = QtWidgets.QLabel(self.horizontalLayoutWidget_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_20.addWidget(self.label_35)
        self.countStatisticsPieChartLimit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countStatisticsPieChartLimit.sizePolicy().hasHeightForWidth())
        self.countStatisticsPieChartLimit.setSizePolicy(sizePolicy)
        self.countStatisticsPieChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.countStatisticsPieChartLimit.setObjectName("countStatisticsPieChartLimit")
        self.horizontalLayout_20.addWidget(self.countStatisticsPieChartLimit)
        self.label_36 = QtWidgets.QLabel(self.horizontalLayoutWidget_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_20.addWidget(self.label_36)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem1)
        self.repaintCountStatisticsPieChartButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_20)
        self.repaintCountStatisticsPieChartButton.setObjectName("repaintCountStatisticsPieChartButton")
        self.horizontalLayout_20.addWidget(self.repaintCountStatisticsPieChartButton)
        self.tabWidget_8.addTab(self.countStatisticsPieChartTab, "")
        self.stackedWidget.addWidget(self.countStatisticsPage)
        self.oddEvenPage = QtWidgets.QWidget()
        self.oddEvenPage.setObjectName("oddEvenPage")
        self.tabWidget = QtWidgets.QTabWidget(self.oddEvenPage)
        self.tabWidget.setGeometry(QtCore.QRect(0, 40, 771, 601))
        self.tabWidget.setObjectName("tabWidget")
        self.oddEvenTableTab = QtWidgets.QWidget()
        self.oddEvenTableTab.setObjectName("oddEvenTableTab")
        self.oddEvenTable = QtWidgets.QTableWidget(self.oddEvenTableTab)
        self.oddEvenTable.setGeometry(QtCore.QRect(-1, -1, 771, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oddEvenTable.sizePolicy().hasHeightForWidth())
        self.oddEvenTable.setSizePolicy(sizePolicy)
        self.oddEvenTable.setObjectName("oddEvenTable")
        self.oddEvenTable.setColumnCount(0)
        self.oddEvenTable.setRowCount(0)
        self.exportOddEven = QtWidgets.QPushButton(self.oddEvenTableTab)
        self.exportOddEven.setGeometry(QtCore.QRect(310, 520, 161, 32))
        self.exportOddEven.setObjectName("exportOddEven")
        self.tabWidget.addTab(self.oddEvenTableTab, "")
        self.oddEvenBarChartTab = QtWidgets.QWidget()
        self.oddEvenBarChartTab.setObjectName("oddEvenBarChartTab")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.oddEvenBarChartTab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(280, 480, 221, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.oddEvenBarChartLimit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oddEvenBarChartLimit.sizePolicy().hasHeightForWidth())
        self.oddEvenBarChartLimit.setSizePolicy(sizePolicy)
        self.oddEvenBarChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.oddEvenBarChartLimit.setObjectName("oddEvenBarChartLimit")
        self.horizontalLayout_3.addWidget(self.oddEvenBarChartLimit)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.repaintOddEvenBarChartButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.repaintOddEvenBarChartButton.setObjectName("repaintOddEvenBarChartButton")
        self.horizontalLayout_3.addWidget(self.repaintOddEvenBarChartButton)
        self.tabWidget.addTab(self.oddEvenBarChartTab, "")
        self.oddEvenPieChartTab = QtWidgets.QWidget()
        self.oddEvenPieChartTab.setObjectName("oddEvenPieChartTab")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.oddEvenPieChartTab)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(270, 480, 221, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.oddEvenPieChartLimit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oddEvenPieChartLimit.sizePolicy().hasHeightForWidth())
        self.oddEvenPieChartLimit.setSizePolicy(sizePolicy)
        self.oddEvenPieChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.oddEvenPieChartLimit.setObjectName("oddEvenPieChartLimit")
        self.horizontalLayout_6.addWidget(self.oddEvenPieChartLimit)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.repaintOddEvenPieChartButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.repaintOddEvenPieChartButton.setObjectName("repaintOddEvenPieChartButton")
        self.horizontalLayout_6.addWidget(self.repaintOddEvenPieChartButton)
        self.tabWidget.addTab(self.oddEvenPieChartTab, "")
        self.stackedWidget.addWidget(self.oddEvenPage)
        self.bigSmallPage = QtWidgets.QWidget()
        self.bigSmallPage.setObjectName("bigSmallPage")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.bigSmallPage)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 40, 771, 601))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.bigSmallTableTab = QtWidgets.QWidget()
        self.bigSmallTableTab.setObjectName("bigSmallTableTab")
        self.bigSmallTable = QtWidgets.QTableWidget(self.bigSmallTableTab)
        self.bigSmallTable.setGeometry(QtCore.QRect(-1, -1, 771, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bigSmallTable.sizePolicy().hasHeightForWidth())
        self.bigSmallTable.setSizePolicy(sizePolicy)
        self.bigSmallTable.setObjectName("bigSmallTable")
        self.bigSmallTable.setColumnCount(0)
        self.bigSmallTable.setRowCount(0)
        self.exportBigSmall = QtWidgets.QPushButton(self.bigSmallTableTab)
        self.exportBigSmall.setGeometry(QtCore.QRect(310, 520, 161, 32))
        self.exportBigSmall.setObjectName("exportBigSmall")
        self.tabWidget_2.addTab(self.bigSmallTableTab, "")
        self.bigSmallBarChartTab = QtWidgets.QWidget()
        self.bigSmallBarChartTab.setObjectName("bigSmallBarChartTab")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.bigSmallBarChartTab)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(280, 480, 221, 51))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.bigSmallBarChartLimit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bigSmallBarChartLimit.sizePolicy().hasHeightForWidth())
        self.bigSmallBarChartLimit.setSizePolicy(sizePolicy)
        self.bigSmallBarChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.bigSmallBarChartLimit.setObjectName("bigSmallBarChartLimit")
        self.horizontalLayout_4.addWidget(self.bigSmallBarChartLimit)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.repaintBigSmallBarChartButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.repaintBigSmallBarChartButton.setObjectName("repaintBigSmallBarChartButton")
        self.horizontalLayout_4.addWidget(self.repaintBigSmallBarChartButton)
        self.tabWidget_2.addTab(self.bigSmallBarChartTab, "")
        self.bigSmallPieChartTab = QtWidgets.QWidget()
        self.bigSmallPieChartTab.setObjectName("bigSmallPieChartTab")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.bigSmallPieChartTab)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(270, 480, 221, 51))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.bigSmallPieChartLimit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bigSmallPieChartLimit.sizePolicy().hasHeightForWidth())
        self.bigSmallPieChartLimit.setSizePolicy(sizePolicy)
        self.bigSmallPieChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.bigSmallPieChartLimit.setObjectName("bigSmallPieChartLimit")
        self.horizontalLayout_7.addWidget(self.bigSmallPieChartLimit)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.repaintBigSmallPieChartButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.repaintBigSmallPieChartButton.setObjectName("repaintBigSmallPieChartButton")
        self.horizontalLayout_7.addWidget(self.repaintBigSmallPieChartButton)
        self.tabWidget_2.addTab(self.bigSmallPieChartTab, "")
        self.stackedWidget.addWidget(self.bigSmallPage)
        self.yinYangPage = QtWidgets.QWidget()
        self.yinYangPage.setObjectName("yinYangPage")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.yinYangPage)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 40, 771, 601))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.yinYangTableTab = QtWidgets.QWidget()
        self.yinYangTableTab.setObjectName("yinYangTableTab")
        self.yinYangTable = QtWidgets.QTableWidget(self.yinYangTableTab)
        self.yinYangTable.setGeometry(QtCore.QRect(-1, -1, 771, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yinYangTable.sizePolicy().hasHeightForWidth())
        self.yinYangTable.setSizePolicy(sizePolicy)
        self.yinYangTable.setObjectName("yinYangTable")
        self.yinYangTable.setColumnCount(0)
        self.yinYangTable.setRowCount(0)
        self.exportYinYang = QtWidgets.QPushButton(self.yinYangTableTab)
        self.exportYinYang.setGeometry(QtCore.QRect(310, 520, 161, 32))
        self.exportYinYang.setObjectName("exportYinYang")
        self.tabWidget_3.addTab(self.yinYangTableTab, "")
        self.yinYangBarChartTab = QtWidgets.QWidget()
        self.yinYangBarChartTab.setObjectName("yinYangBarChartTab")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.yinYangBarChartTab)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(280, 480, 221, 51))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.yinYangBarChartLimit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yinYangBarChartLimit.sizePolicy().hasHeightForWidth())
        self.yinYangBarChartLimit.setSizePolicy(sizePolicy)
        self.yinYangBarChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.yinYangBarChartLimit.setObjectName("yinYangBarChartLimit")
        self.horizontalLayout_5.addWidget(self.yinYangBarChartLimit)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.repaintYinYangBarChartButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.repaintYinYangBarChartButton.setObjectName("repaintYinYangBarChartButton")
        self.horizontalLayout_5.addWidget(self.repaintYinYangBarChartButton)
        self.tabWidget_3.addTab(self.yinYangBarChartTab, "")
        self.yinYangPieChartTab = QtWidgets.QWidget()
        self.yinYangPieChartTab.setObjectName("yinYangPieChartTab")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.yinYangPieChartTab)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(270, 480, 221, 51))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.yinYangPieChartLimit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yinYangPieChartLimit.sizePolicy().hasHeightForWidth())
        self.yinYangPieChartLimit.setSizePolicy(sizePolicy)
        self.yinYangPieChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.yinYangPieChartLimit.setObjectName("yinYangPieChartLimit")
        self.horizontalLayout_8.addWidget(self.yinYangPieChartLimit)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.repaintYinYangPieChartButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.repaintYinYangPieChartButton.setObjectName("repaintYinYangPieChartButton")
        self.horizontalLayout_8.addWidget(self.repaintYinYangPieChartButton)
        self.tabWidget_3.addTab(self.yinYangPieChartTab, "")
        self.stackedWidget.addWidget(self.yinYangPage)
        self.primeCompositePage = QtWidgets.QWidget()
        self.primeCompositePage.setObjectName("primeCompositePage")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.primeCompositePage)
        self.tabWidget_4.setGeometry(QtCore.QRect(0, 40, 771, 601))
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.primeCompositeTableTab = QtWidgets.QWidget()
        self.primeCompositeTableTab.setObjectName("primeCompositeTableTab")
        self.primeCompositeTable = QtWidgets.QTableWidget(self.primeCompositeTableTab)
        self.primeCompositeTable.setGeometry(QtCore.QRect(-1, -1, 771, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.primeCompositeTable.sizePolicy().hasHeightForWidth())
        self.primeCompositeTable.setSizePolicy(sizePolicy)
        self.primeCompositeTable.setObjectName("primeCompositeTable")
        self.primeCompositeTable.setColumnCount(0)
        self.primeCompositeTable.setRowCount(0)
        self.exportPrimeComposite = QtWidgets.QPushButton(self.primeCompositeTableTab)
        self.exportPrimeComposite.setGeometry(QtCore.QRect(310, 520, 161, 32))
        self.exportPrimeComposite.setObjectName("exportPrimeComposite")
        self.tabWidget_4.addTab(self.primeCompositeTableTab, "")
        self.primeCompositeBarChartTab = QtWidgets.QWidget()
        self.primeCompositeBarChartTab.setObjectName("primeCompositeBarChartTab")
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.primeCompositeBarChartTab)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(280, 480, 221, 51))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.primeCompositeBarChartLimit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.primeCompositeBarChartLimit.sizePolicy().hasHeightForWidth())
        self.primeCompositeBarChartLimit.setSizePolicy(sizePolicy)
        self.primeCompositeBarChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.primeCompositeBarChartLimit.setObjectName("primeCompositeBarChartLimit")
        self.horizontalLayout_9.addWidget(self.primeCompositeBarChartLimit)
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.repaintPrimeCompositeBarChartButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        self.repaintPrimeCompositeBarChartButton.setObjectName("repaintPrimeCompositeBarChartButton")
        self.horizontalLayout_9.addWidget(self.repaintPrimeCompositeBarChartButton)
        self.tabWidget_4.addTab(self.primeCompositeBarChartTab, "")
        self.primeCompositePieChartTab = QtWidgets.QWidget()
        self.primeCompositePieChartTab.setObjectName("primeCompositePieChartTab")
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.primeCompositePieChartTab)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(270, 480, 221, 51))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_10.addWidget(self.label_15)
        self.primeCompositePieChartLimit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.primeCompositePieChartLimit.sizePolicy().hasHeightForWidth())
        self.primeCompositePieChartLimit.setSizePolicy(sizePolicy)
        self.primeCompositePieChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.primeCompositePieChartLimit.setObjectName("primeCompositePieChartLimit")
        self.horizontalLayout_10.addWidget(self.primeCompositePieChartLimit)
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_10.addWidget(self.label_16)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.repaintPrimeCompositePieChartButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_10)
        self.repaintPrimeCompositePieChartButton.setObjectName("repaintPrimeCompositePieChartButton")
        self.horizontalLayout_10.addWidget(self.repaintPrimeCompositePieChartButton)
        self.tabWidget_4.addTab(self.primeCompositePieChartTab, "")
        self.stackedWidget.addWidget(self.primeCompositePage)
        self.calcSumPage = QtWidgets.QWidget()
        self.calcSumPage.setObjectName("calcSumPage")
        self.tabWidget_7 = QtWidgets.QTabWidget(self.calcSumPage)
        self.tabWidget_7.setGeometry(QtCore.QRect(0, 40, 771, 601))
        self.tabWidget_7.setObjectName("tabWidget_7")
        self.calcSumTableTab = QtWidgets.QWidget()
        self.calcSumTableTab.setObjectName("calcSumTableTab")
        self.calcSumTable = QtWidgets.QTableWidget(self.calcSumTableTab)
        self.calcSumTable.setGeometry(QtCore.QRect(-1, -1, 771, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calcSumTable.sizePolicy().hasHeightForWidth())
        self.calcSumTable.setSizePolicy(sizePolicy)
        self.calcSumTable.setObjectName("calcSumTable")
        self.calcSumTable.setColumnCount(0)
        self.calcSumTable.setRowCount(0)
        self.exportCalcSum = QtWidgets.QPushButton(self.calcSumTableTab)
        self.exportCalcSum.setGeometry(QtCore.QRect(310, 520, 161, 32))
        self.exportCalcSum.setObjectName("exportCalcSum")
        self.tabWidget_7.addTab(self.calcSumTableTab, "")
        self.calcSumBarChartTab = QtWidgets.QWidget()
        self.calcSumBarChartTab.setObjectName("calcSumBarChartTab")
        self.horizontalLayoutWidget_17 = QtWidgets.QWidget(self.calcSumBarChartTab)
        self.horizontalLayoutWidget_17.setGeometry(QtCore.QRect(280, 480, 221, 51))
        self.horizontalLayoutWidget_17.setObjectName("horizontalLayoutWidget_17")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_17)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_29 = QtWidgets.QLabel(self.horizontalLayoutWidget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_17.addWidget(self.label_29)
        self.calcSumBarChartLimit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calcSumBarChartLimit.sizePolicy().hasHeightForWidth())
        self.calcSumBarChartLimit.setSizePolicy(sizePolicy)
        self.calcSumBarChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.calcSumBarChartLimit.setObjectName("calcSumBarChartLimit")
        self.horizontalLayout_17.addWidget(self.calcSumBarChartLimit)
        self.label_30 = QtWidgets.QLabel(self.horizontalLayoutWidget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_17.addWidget(self.label_30)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem10)
        self.repaintCalcSumBarChartButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_17)
        self.repaintCalcSumBarChartButton.setObjectName("repaintCalcSumBarChartButton")
        self.horizontalLayout_17.addWidget(self.repaintCalcSumBarChartButton)
        self.tabWidget_7.addTab(self.calcSumBarChartTab, "")
        self.calcSumPieChartTab = QtWidgets.QWidget()
        self.calcSumPieChartTab.setObjectName("calcSumPieChartTab")
        self.horizontalLayoutWidget_18 = QtWidgets.QWidget(self.calcSumPieChartTab)
        self.horizontalLayoutWidget_18.setGeometry(QtCore.QRect(270, 480, 221, 51))
        self.horizontalLayoutWidget_18.setObjectName("horizontalLayoutWidget_18")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_18)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_31 = QtWidgets.QLabel(self.horizontalLayoutWidget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_18.addWidget(self.label_31)
        self.calcSumPieChartLimit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calcSumPieChartLimit.sizePolicy().hasHeightForWidth())
        self.calcSumPieChartLimit.setSizePolicy(sizePolicy)
        self.calcSumPieChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.calcSumPieChartLimit.setObjectName("calcSumPieChartLimit")
        self.horizontalLayout_18.addWidget(self.calcSumPieChartLimit)
        self.label_32 = QtWidgets.QLabel(self.horizontalLayoutWidget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_18.addWidget(self.label_32)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem11)
        self.repaintCalcSumPieChartButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_18)
        self.repaintCalcSumPieChartButton.setObjectName("repaintCalcSumPieChartButton")
        self.horizontalLayout_18.addWidget(self.repaintCalcSumPieChartButton)
        self.tabWidget_7.addTab(self.calcSumPieChartTab, "")
        self.stackedWidget.addWidget(self.calcSumPage)
        self.calc012Page = QtWidgets.QWidget()
        self.calc012Page.setObjectName("calc012Page")
        self.tabWidget_5 = QtWidgets.QTabWidget(self.calc012Page)
        self.tabWidget_5.setGeometry(QtCore.QRect(0, 40, 771, 601))
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.calc012TableTab = QtWidgets.QWidget()
        self.calc012TableTab.setObjectName("calc012TableTab")
        self.calc012Table = QtWidgets.QTableWidget(self.calc012TableTab)
        self.calc012Table.setGeometry(QtCore.QRect(-1, -1, 771, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calc012Table.sizePolicy().hasHeightForWidth())
        self.calc012Table.setSizePolicy(sizePolicy)
        self.calc012Table.setObjectName("calc012Table")
        self.calc012Table.setColumnCount(0)
        self.calc012Table.setRowCount(0)
        self.exportCalc012 = QtWidgets.QPushButton(self.calc012TableTab)
        self.exportCalc012.setGeometry(QtCore.QRect(310, 520, 161, 32))
        self.exportCalc012.setObjectName("exportCalc012")
        self.tabWidget_5.addTab(self.calc012TableTab, "")
        self.calc012BarChartTab = QtWidgets.QWidget()
        self.calc012BarChartTab.setObjectName("calc012BarChartTab")
        self.horizontalLayoutWidget_13 = QtWidgets.QWidget(self.calc012BarChartTab)
        self.horizontalLayoutWidget_13.setGeometry(QtCore.QRect(280, 480, 221, 51))
        self.horizontalLayoutWidget_13.setObjectName("horizontalLayoutWidget_13")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_13)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_13.addWidget(self.label_21)
        self.calc012BarChartLimit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calc012BarChartLimit.sizePolicy().hasHeightForWidth())
        self.calc012BarChartLimit.setSizePolicy(sizePolicy)
        self.calc012BarChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.calc012BarChartLimit.setObjectName("calc012BarChartLimit")
        self.horizontalLayout_13.addWidget(self.calc012BarChartLimit)
        self.label_22 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_13.addWidget(self.label_22)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem12)
        self.repaintCalc012BarChartButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_13)
        self.repaintCalc012BarChartButton.setObjectName("repaintCalc012BarChartButton")
        self.horizontalLayout_13.addWidget(self.repaintCalc012BarChartButton)
        self.tabWidget_5.addTab(self.calc012BarChartTab, "")
        self.calc012PieChartTab = QtWidgets.QWidget()
        self.calc012PieChartTab.setObjectName("calc012PieChartTab")
        self.horizontalLayoutWidget_14 = QtWidgets.QWidget(self.calc012PieChartTab)
        self.horizontalLayoutWidget_14.setGeometry(QtCore.QRect(270, 480, 221, 51))
        self.horizontalLayoutWidget_14.setObjectName("horizontalLayoutWidget_14")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_14)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_23 = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_14.addWidget(self.label_23)
        self.calc012PieChartLimit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calc012PieChartLimit.sizePolicy().hasHeightForWidth())
        self.calc012PieChartLimit.setSizePolicy(sizePolicy)
        self.calc012PieChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.calc012PieChartLimit.setObjectName("calc012PieChartLimit")
        self.horizontalLayout_14.addWidget(self.calc012PieChartLimit)
        self.label_24 = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_14.addWidget(self.label_24)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem13)
        self.repaintCalc012PieChartButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_14)
        self.repaintCalc012PieChartButton.setObjectName("repaintCalc012PieChartButton")
        self.horizontalLayout_14.addWidget(self.repaintCalc012PieChartButton)
        self.tabWidget_5.addTab(self.calc012PieChartTab, "")
        self.stackedWidget.addWidget(self.calc012Page)
        self.calcSpanPage = QtWidgets.QWidget()
        self.calcSpanPage.setObjectName("calcSpanPage")
        self.tabWidget_6 = QtWidgets.QTabWidget(self.calcSpanPage)
        self.tabWidget_6.setGeometry(QtCore.QRect(0, 40, 771, 601))
        self.tabWidget_6.setObjectName("tabWidget_6")
        self.calcSpanTableTab = QtWidgets.QWidget()
        self.calcSpanTableTab.setObjectName("calcSpanTableTab")
        self.calcSpanTable = QtWidgets.QTableWidget(self.calcSpanTableTab)
        self.calcSpanTable.setGeometry(QtCore.QRect(-1, -1, 771, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calcSpanTable.sizePolicy().hasHeightForWidth())
        self.calcSpanTable.setSizePolicy(sizePolicy)
        self.calcSpanTable.setObjectName("calcSpanTable")
        self.calcSpanTable.setColumnCount(0)
        self.calcSpanTable.setRowCount(0)
        self.exportCalcSpan = QtWidgets.QPushButton(self.calcSpanTableTab)
        self.exportCalcSpan.setGeometry(QtCore.QRect(310, 520, 161, 32))
        self.exportCalcSpan.setObjectName("exportCalcSpan")
        self.tabWidget_6.addTab(self.calcSpanTableTab, "")
        self.calcSpanBarChartTab = QtWidgets.QWidget()
        self.calcSpanBarChartTab.setObjectName("calcSpanBarChartTab")
        self.horizontalLayoutWidget_15 = QtWidgets.QWidget(self.calcSpanBarChartTab)
        self.horizontalLayoutWidget_15.setGeometry(QtCore.QRect(280, 480, 221, 51))
        self.horizontalLayoutWidget_15.setObjectName("horizontalLayoutWidget_15")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_15)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_25 = QtWidgets.QLabel(self.horizontalLayoutWidget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_15.addWidget(self.label_25)
        self.calcSpanBarChartLimit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calcSpanBarChartLimit.sizePolicy().hasHeightForWidth())
        self.calcSpanBarChartLimit.setSizePolicy(sizePolicy)
        self.calcSpanBarChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.calcSpanBarChartLimit.setObjectName("calcSpanBarChartLimit")
        self.horizontalLayout_15.addWidget(self.calcSpanBarChartLimit)
        self.label_26 = QtWidgets.QLabel(self.horizontalLayoutWidget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_15.addWidget(self.label_26)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem14)
        self.repaintCalcSpanBarChartButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_15)
        self.repaintCalcSpanBarChartButton.setObjectName("repaintCalcSpanBarChartButton")
        self.horizontalLayout_15.addWidget(self.repaintCalcSpanBarChartButton)
        self.tabWidget_6.addTab(self.calcSpanBarChartTab, "")
        self.calcSpanPieChartTab = QtWidgets.QWidget()
        self.calcSpanPieChartTab.setObjectName("calcSpanPieChartTab")
        self.horizontalLayoutWidget_16 = QtWidgets.QWidget(self.calcSpanPieChartTab)
        self.horizontalLayoutWidget_16.setGeometry(QtCore.QRect(270, 480, 221, 51))
        self.horizontalLayoutWidget_16.setObjectName("horizontalLayoutWidget_16")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_16)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_27 = QtWidgets.QLabel(self.horizontalLayoutWidget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_16.addWidget(self.label_27)
        self.calcSpanPieChartLimit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calcSpanPieChartLimit.sizePolicy().hasHeightForWidth())
        self.calcSpanPieChartLimit.setSizePolicy(sizePolicy)
        self.calcSpanPieChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.calcSpanPieChartLimit.setObjectName("calcSpanPieChartLimit")
        self.horizontalLayout_16.addWidget(self.calcSpanPieChartLimit)
        self.label_28 = QtWidgets.QLabel(self.horizontalLayoutWidget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_16.addWidget(self.label_28)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem15)
        self.repaintCalcSpanPieChartButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_16)
        self.repaintCalcSpanPieChartButton.setObjectName("repaintCalcSpanPieChartButton")
        self.horizontalLayout_16.addWidget(self.repaintCalcSpanPieChartButton)
        self.tabWidget_6.addTab(self.calcSpanPieChartTab, "")
        self.stackedWidget.addWidget(self.calcSpanPage)
        self.horizontalLayout.addWidget(self.rightFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.tabWidget_8.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_7.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(0)
        self.tabWidget_6.setCurrentIndex(0)
        self.menuList.currentRowChanged['int'].connect(self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        __sortingEnabled = self.menuList.isSortingEnabled()
        self.menuList.setSortingEnabled(False)
        item = self.menuList.item(0)
        item.setText(_translate("MainWindow", "数据总览"))
        item = self.menuList.item(1)
        item.setText(_translate("MainWindow", "号码出现次数"))
        item = self.menuList.item(2)
        item.setText(_translate("MainWindow", "次数统计"))
        item = self.menuList.item(3)
        item.setText(_translate("MainWindow", "奇偶"))
        item = self.menuList.item(4)
        item.setText(_translate("MainWindow", "大小"))
        item = self.menuList.item(5)
        item.setText(_translate("MainWindow", "阴阳"))
        item = self.menuList.item(6)
        item.setText(_translate("MainWindow", "质合"))
        item = self.menuList.item(7)
        item.setText(_translate("MainWindow", "和值"))
        item = self.menuList.item(8)
        item.setText(_translate("MainWindow", "012路"))
        item = self.menuList.item(9)
        item.setText(_translate("MainWindow", "跨度"))
        self.menuList.setSortingEnabled(__sortingEnabled)
        self.updateData.setText(_translate("MainWindow", "更新数据"))
        self.exportAllData.setText(_translate("MainWindow", "导出为 excel"))
        self.perNumberCountTable.setSortingEnabled(True)
        self.exportPerNumberCount.setText(_translate("MainWindow", "导出为 excel"))
        self.exportCountStatistics.setText(_translate("MainWindow", "导出为 excel"))
        self.tabWidget_8.setTabText(self.tabWidget_8.indexOf(self.countStatisticsTableTab), _translate("MainWindow", "表格"))
        self.label_33.setText(_translate("MainWindow", "最近"))
        self.label_34.setText(_translate("MainWindow", "期"))
        self.repaintCountStatisticsBarChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_8.setTabText(self.tabWidget_8.indexOf(self.countStatisticsBarChartTab), _translate("MainWindow", "柱形图"))
        self.label_35.setText(_translate("MainWindow", "最近"))
        self.label_36.setText(_translate("MainWindow", "期"))
        self.repaintCountStatisticsPieChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_8.setTabText(self.tabWidget_8.indexOf(self.countStatisticsPieChartTab), _translate("MainWindow", "扇形图"))
        self.exportOddEven.setText(_translate("MainWindow", "导出为 excel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.oddEvenTableTab), _translate("MainWindow", "表格"))
        self.label_2.setText(_translate("MainWindow", "最近"))
        self.label.setText(_translate("MainWindow", "期"))
        self.repaintOddEvenBarChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.oddEvenBarChartTab), _translate("MainWindow", "柱形图"))
        self.label_7.setText(_translate("MainWindow", "最近"))
        self.label_8.setText(_translate("MainWindow", "期"))
        self.repaintOddEvenPieChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.oddEvenPieChartTab), _translate("MainWindow", "扇形图"))
        self.exportBigSmall.setText(_translate("MainWindow", "导出为 excel"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.bigSmallTableTab), _translate("MainWindow", "表格"))
        self.label_3.setText(_translate("MainWindow", "最近"))
        self.label_4.setText(_translate("MainWindow", "期"))
        self.repaintBigSmallBarChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.bigSmallBarChartTab), _translate("MainWindow", "柱形图"))
        self.label_9.setText(_translate("MainWindow", "最近"))
        self.label_10.setText(_translate("MainWindow", "期"))
        self.repaintBigSmallPieChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.bigSmallPieChartTab), _translate("MainWindow", "扇形图"))
        self.exportYinYang.setText(_translate("MainWindow", "导出为 excel"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.yinYangTableTab), _translate("MainWindow", "表格"))
        self.label_5.setText(_translate("MainWindow", "最近"))
        self.label_6.setText(_translate("MainWindow", "期"))
        self.repaintYinYangBarChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.yinYangBarChartTab), _translate("MainWindow", "柱形图"))
        self.label_11.setText(_translate("MainWindow", "最近"))
        self.label_12.setText(_translate("MainWindow", "期"))
        self.repaintYinYangPieChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.yinYangPieChartTab), _translate("MainWindow", "扇形图"))
        self.exportPrimeComposite.setText(_translate("MainWindow", "导出为 excel"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.primeCompositeTableTab), _translate("MainWindow", "表格"))
        self.label_13.setText(_translate("MainWindow", "最近"))
        self.label_14.setText(_translate("MainWindow", "期"))
        self.repaintPrimeCompositeBarChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.primeCompositeBarChartTab), _translate("MainWindow", "柱形图"))
        self.label_15.setText(_translate("MainWindow", "最近"))
        self.label_16.setText(_translate("MainWindow", "期"))
        self.repaintPrimeCompositePieChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.primeCompositePieChartTab), _translate("MainWindow", "扇形图"))
        self.exportCalcSum.setText(_translate("MainWindow", "导出为 excel"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.calcSumTableTab), _translate("MainWindow", "表格"))
        self.label_29.setText(_translate("MainWindow", "最近"))
        self.label_30.setText(_translate("MainWindow", "期"))
        self.repaintCalcSumBarChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.calcSumBarChartTab), _translate("MainWindow", "柱形图"))
        self.label_31.setText(_translate("MainWindow", "最近"))
        self.label_32.setText(_translate("MainWindow", "期"))
        self.repaintCalcSumPieChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.calcSumPieChartTab), _translate("MainWindow", "扇形图"))
        self.exportCalc012.setText(_translate("MainWindow", "导出为 excel"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.calc012TableTab), _translate("MainWindow", "表格"))
        self.label_21.setText(_translate("MainWindow", "最近"))
        self.label_22.setText(_translate("MainWindow", "期"))
        self.repaintCalc012BarChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.calc012BarChartTab), _translate("MainWindow", "柱形图"))
        self.label_23.setText(_translate("MainWindow", "最近"))
        self.label_24.setText(_translate("MainWindow", "期"))
        self.repaintCalc012PieChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.calc012PieChartTab), _translate("MainWindow", "扇形图"))
        self.exportCalcSpan.setText(_translate("MainWindow", "导出为 excel"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.calcSpanTableTab), _translate("MainWindow", "表格"))
        self.label_25.setText(_translate("MainWindow", "最近"))
        self.label_26.setText(_translate("MainWindow", "期"))
        self.repaintCalcSpanBarChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.calcSpanBarChartTab), _translate("MainWindow", "柱形图"))
        self.label_27.setText(_translate("MainWindow", "最近"))
        self.label_28.setText(_translate("MainWindow", "期"))
        self.repaintCalcSpanPieChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.calcSpanPieChartTab), _translate("MainWindow", "扇形图"))
