# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/160ACB750ACB5083/Git_Repo/3D_福彩/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1160, 669)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 1161, 671))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftFrame = QtWidgets.QFrame(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftFrame.sizePolicy().hasHeightForWidth())
        self.leftFrame.setSizePolicy(sizePolicy)
        self.leftFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftFrame.setObjectName("leftFrame")
        self.menuList = QtWidgets.QListWidget(self.leftFrame)
        self.menuList.setGeometry(QtCore.QRect(30, 40, 281, 581))
        self.menuList.setStyleSheet("")
        self.menuList.setObjectName("menuList")
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        self.horizontalLayout.addWidget(self.leftFrame)
        self.line = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.rightFrame = QtWidgets.QFrame(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightFrame.sizePolicy().hasHeightForWidth())
        self.rightFrame.setSizePolicy(sizePolicy)
        self.rightFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightFrame.setObjectName("rightFrame")
        self.stackedWidget = QtWidgets.QStackedWidget(self.rightFrame)
        self.stackedWidget.setGeometry(QtCore.QRect(19, -21, 771, 671))
        self.stackedWidget.setObjectName("stackedWidget")
        self.allDataPage = QtWidgets.QWidget()
        self.allDataPage.setObjectName("allDataPage")
        self.allDataTable = QtWidgets.QTableWidget(self.allDataPage)
        self.allDataTable.setGeometry(QtCore.QRect(5, 61, 751, 521))
        self.allDataTable.setObjectName("allDataTable")
        self.allDataTable.setColumnCount(0)
        self.allDataTable.setRowCount(0)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.allDataPage)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(220, 610, 351, 34))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.updateData = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.updateData.setObjectName("updateData")
        self.horizontalLayout_2.addWidget(self.updateData)
        self.exportAllData = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.exportAllData.setObjectName("exportAllData")
        self.horizontalLayout_2.addWidget(self.exportAllData)
        self.stackedWidget.addWidget(self.allDataPage)
        self.perNumberCountPage = QtWidgets.QWidget()
        self.perNumberCountPage.setObjectName("perNumberCountPage")
        self.perNumberCountTable = QtWidgets.QTableWidget(self.perNumberCountPage)
        self.perNumberCountTable.setGeometry(QtCore.QRect(5, 61, 751, 531))
        self.perNumberCountTable.setObjectName("perNumberCountTable")
        self.perNumberCountTable.setColumnCount(0)
        self.perNumberCountTable.setRowCount(0)
        self.perNumberCountTable.horizontalHeader().setDefaultSectionSize(350)
        self.exportPerNumberCount = QtWidgets.QPushButton(self.perNumberCountPage)
        self.exportPerNumberCount.setGeometry(QtCore.QRect(310, 610, 141, 32))
        self.exportPerNumberCount.setObjectName("exportPerNumberCount")
        self.stackedWidget.addWidget(self.perNumberCountPage)
        self.countStatisticsPage = QtWidgets.QWidget()
        self.countStatisticsPage.setObjectName("countStatisticsPage")
        self.stackedWidget.addWidget(self.countStatisticsPage)
        self.oddEvenPage = QtWidgets.QWidget()
        self.oddEvenPage.setObjectName("oddEvenPage")
        self.tabWidget = QtWidgets.QTabWidget(self.oddEvenPage)
        self.tabWidget.setGeometry(QtCore.QRect(0, 40, 771, 601))
        self.tabWidget.setObjectName("tabWidget")
        self.oddEvenTableTab = QtWidgets.QWidget()
        self.oddEvenTableTab.setObjectName("oddEvenTableTab")
        self.oddEvenTable = QtWidgets.QTableWidget(self.oddEvenTableTab)
        self.oddEvenTable.setGeometry(QtCore.QRect(-1, -1, 771, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oddEvenTable.sizePolicy().hasHeightForWidth())
        self.oddEvenTable.setSizePolicy(sizePolicy)
        self.oddEvenTable.setObjectName("oddEvenTable")
        self.oddEvenTable.setColumnCount(0)
        self.oddEvenTable.setRowCount(0)
        self.exportOddEven = QtWidgets.QPushButton(self.oddEvenTableTab)
        self.exportOddEven.setGeometry(QtCore.QRect(310, 520, 161, 32))
        self.exportOddEven.setObjectName("exportOddEven")
        self.tabWidget.addTab(self.oddEvenTableTab, "")
        self.oddEvenBarChartTab = QtWidgets.QWidget()
        self.oddEvenBarChartTab.setObjectName("oddEvenBarChartTab")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.oddEvenBarChartTab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(280, 480, 221, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.oddEvenBarChartLimit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oddEvenBarChartLimit.sizePolicy().hasHeightForWidth())
        self.oddEvenBarChartLimit.setSizePolicy(sizePolicy)
        self.oddEvenBarChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.oddEvenBarChartLimit.setObjectName("oddEvenBarChartLimit")
        self.horizontalLayout_3.addWidget(self.oddEvenBarChartLimit)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.repaintOddEvenBarChartButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.repaintOddEvenBarChartButton.setObjectName("repaintOddEvenBarChartButton")
        self.horizontalLayout_3.addWidget(self.repaintOddEvenBarChartButton)
        self.tabWidget.addTab(self.oddEvenBarChartTab, "")
        self.oddEvenPieChartTab = QtWidgets.QWidget()
        self.oddEvenPieChartTab.setObjectName("oddEvenPieChartTab")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.oddEvenPieChartTab)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(270, 480, 221, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.oddEvenPieChartLimit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oddEvenPieChartLimit.sizePolicy().hasHeightForWidth())
        self.oddEvenPieChartLimit.setSizePolicy(sizePolicy)
        self.oddEvenPieChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.oddEvenPieChartLimit.setObjectName("oddEvenPieChartLimit")
        self.horizontalLayout_6.addWidget(self.oddEvenPieChartLimit)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.repaintOddEvenPieChartButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.repaintOddEvenPieChartButton.setObjectName("repaintOddEvenPieChartButton")
        self.horizontalLayout_6.addWidget(self.repaintOddEvenPieChartButton)
        self.tabWidget.addTab(self.oddEvenPieChartTab, "")
        self.stackedWidget.addWidget(self.oddEvenPage)
        self.bigSmallPage = QtWidgets.QWidget()
        self.bigSmallPage.setObjectName("bigSmallPage")
        self.stackedWidget.addWidget(self.bigSmallPage)
        self.yinYangPage = QtWidgets.QWidget()
        self.yinYangPage.setObjectName("yinYangPage")
        self.stackedWidget.addWidget(self.yinYangPage)
        self.primeCompositePage = QtWidgets.QWidget()
        self.primeCompositePage.setObjectName("primeCompositePage")
        self.stackedWidget.addWidget(self.primeCompositePage)
        self.calcSumPage = QtWidgets.QWidget()
        self.calcSumPage.setObjectName("calcSumPage")
        self.stackedWidget.addWidget(self.calcSumPage)
        self.calc012Page = QtWidgets.QWidget()
        self.calc012Page.setObjectName("calc012Page")
        self.stackedWidget.addWidget(self.calc012Page)
        self.calcSpanPage = QtWidgets.QWidget()
        self.calcSpanPage.setObjectName("calcSpanPage")
        self.stackedWidget.addWidget(self.calcSpanPage)
        self.horizontalLayout.addWidget(self.rightFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        self.tabWidget.setCurrentIndex(2)
        self.menuList.currentRowChanged['int'].connect(self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        __sortingEnabled = self.menuList.isSortingEnabled()
        self.menuList.setSortingEnabled(False)
        item = self.menuList.item(0)
        item.setText(_translate("MainWindow", "数据总览"))
        item = self.menuList.item(1)
        item.setText(_translate("MainWindow", "号码出现次数"))
        item = self.menuList.item(2)
        item.setText(_translate("MainWindow", "次数统计"))
        item = self.menuList.item(3)
        item.setText(_translate("MainWindow", "奇偶"))
        item = self.menuList.item(4)
        item.setText(_translate("MainWindow", "大小"))
        item = self.menuList.item(5)
        item.setText(_translate("MainWindow", "阴阳"))
        item = self.menuList.item(6)
        item.setText(_translate("MainWindow", "质合"))
        item = self.menuList.item(7)
        item.setText(_translate("MainWindow", "和值"))
        item = self.menuList.item(8)
        item.setText(_translate("MainWindow", "012路"))
        item = self.menuList.item(9)
        item.setText(_translate("MainWindow", "跨度"))
        self.menuList.setSortingEnabled(__sortingEnabled)
        self.updateData.setText(_translate("MainWindow", "更新数据"))
        self.exportAllData.setText(_translate("MainWindow", "导出为 excel"))
        self.perNumberCountTable.setSortingEnabled(True)
        self.exportPerNumberCount.setText(_translate("MainWindow", "导出为 excel"))
        self.exportOddEven.setText(_translate("MainWindow", "导出为 excel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.oddEvenTableTab), _translate("MainWindow", "表格"))
        self.label_2.setText(_translate("MainWindow", "最近"))
        self.label.setText(_translate("MainWindow", "期"))
        self.repaintOddEvenBarChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.oddEvenBarChartTab), _translate("MainWindow", "柱形图"))
        self.label_7.setText(_translate("MainWindow", "最近"))
        self.label_8.setText(_translate("MainWindow", "期"))
        self.repaintOddEvenPieChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.oddEvenPieChartTab), _translate("MainWindow", "扇形图"))
