# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/160ACB750ACB5083/Git_Repo/3D_福彩/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1169, 686)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftFrame.sizePolicy().hasHeightForWidth())
        self.leftFrame.setSizePolicy(sizePolicy)
        self.leftFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftFrame.setObjectName("leftFrame")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.leftFrame)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.menuList = QtWidgets.QListWidget(self.leftFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuList.sizePolicy().hasHeightForWidth())
        self.menuList.setSizePolicy(sizePolicy)
        self.menuList.setStyleSheet("")
        self.menuList.setObjectName("menuList")
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menuList.addItem(item)
        self.horizontalLayout_11.addWidget(self.menuList)
        self.horizontalLayout.addWidget(self.leftFrame)
        self.rightFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightFrame.sizePolicy().hasHeightForWidth())
        self.rightFrame.setSizePolicy(sizePolicy)
        self.rightFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightFrame.setObjectName("rightFrame")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.rightFrame)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.stackedWidget = QtWidgets.QStackedWidget(self.rightFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.allDataPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allDataPage.sizePolicy().hasHeightForWidth())
        self.allDataPage.setSizePolicy(sizePolicy)
        self.allDataPage.setObjectName("allDataPage")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.allDataPage)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.allDataTable = QtWidgets.QTableWidget(self.allDataPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allDataTable.sizePolicy().hasHeightForWidth())
        self.allDataTable.setSizePolicy(sizePolicy)
        self.allDataTable.setObjectName("allDataTable")
        self.allDataTable.setColumnCount(0)
        self.allDataTable.setRowCount(0)
        self.verticalLayout.addWidget(self.allDataTable)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 30, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.exportAllData = QtWidgets.QPushButton(self.allDataPage)
        self.exportAllData.setObjectName("exportAllData")
        self.horizontalLayout_2.addWidget(self.exportAllData)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.stackedWidget.addWidget(self.allDataPage)
        self.perNumberCountPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.perNumberCountPage.sizePolicy().hasHeightForWidth())
        self.perNumberCountPage.setSizePolicy(sizePolicy)
        self.perNumberCountPage.setObjectName("perNumberCountPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.perNumberCountPage)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.perNumberCountTable = QtWidgets.QTableWidget(self.perNumberCountPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.perNumberCountTable.sizePolicy().hasHeightForWidth())
        self.perNumberCountTable.setSizePolicy(sizePolicy)
        self.perNumberCountTable.setObjectName("perNumberCountTable")
        self.perNumberCountTable.setColumnCount(0)
        self.perNumberCountTable.setRowCount(0)
        self.perNumberCountTable.horizontalHeader().setDefaultSectionSize(125)
        self.verticalLayout_2.addWidget(self.perNumberCountTable)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.exportPerNumberCount = QtWidgets.QPushButton(self.perNumberCountPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportPerNumberCount.sizePolicy().hasHeightForWidth())
        self.exportPerNumberCount.setSizePolicy(sizePolicy)
        self.exportPerNumberCount.setObjectName("exportPerNumberCount")
        self.verticalLayout_2.addWidget(self.exportPerNumberCount)
        self.stackedWidget.addWidget(self.perNumberCountPage)
        self.countStatisticsPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countStatisticsPage.sizePolicy().hasHeightForWidth())
        self.countStatisticsPage.setSizePolicy(sizePolicy)
        self.countStatisticsPage.setObjectName("countStatisticsPage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.countStatisticsPage)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget_8 = QtWidgets.QTabWidget(self.countStatisticsPage)
        self.tabWidget_8.setObjectName("tabWidget_8")
        self.countStatisticsTableTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countStatisticsTableTab.sizePolicy().hasHeightForWidth())
        self.countStatisticsTableTab.setSizePolicy(sizePolicy)
        self.countStatisticsTableTab.setObjectName("countStatisticsTableTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.countStatisticsTableTab)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.countStatisticsTable = QtWidgets.QTableWidget(self.countStatisticsTableTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countStatisticsTable.sizePolicy().hasHeightForWidth())
        self.countStatisticsTable.setSizePolicy(sizePolicy)
        self.countStatisticsTable.setObjectName("countStatisticsTable")
        self.countStatisticsTable.setColumnCount(0)
        self.countStatisticsTable.setRowCount(0)
        self.verticalLayout_4.addWidget(self.countStatisticsTable)
        spacerItem1 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem1)
        self.exportCountStatistics = QtWidgets.QPushButton(self.countStatisticsTableTab)
        self.exportCountStatistics.setObjectName("exportCountStatistics")
        self.verticalLayout_4.addWidget(self.exportCountStatistics)
        self.tabWidget_8.addTab(self.countStatisticsTableTab, "")
        self.countStatisticsBarChartTab = QtWidgets.QWidget()
        self.countStatisticsBarChartTab.setObjectName("countStatisticsBarChartTab")
        self.countStatisticsBarChartTabLayout = QtWidgets.QVBoxLayout(self.countStatisticsBarChartTab)
        self.countStatisticsBarChartTabLayout.setContentsMargins(0, 0, 0, 0)
        self.countStatisticsBarChartTabLayout.setSpacing(0)
        self.countStatisticsBarChartTabLayout.setObjectName("countStatisticsBarChartTabLayout")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_19.setContentsMargins(-1, 30, -1, 50)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem2)
        self.label_33 = QtWidgets.QLabel(self.countStatisticsBarChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_19.addWidget(self.label_33)
        self.countStatisticsBarChartLimit = QtWidgets.QLineEdit(self.countStatisticsBarChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countStatisticsBarChartLimit.sizePolicy().hasHeightForWidth())
        self.countStatisticsBarChartLimit.setSizePolicy(sizePolicy)
        self.countStatisticsBarChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.countStatisticsBarChartLimit.setObjectName("countStatisticsBarChartLimit")
        self.horizontalLayout_19.addWidget(self.countStatisticsBarChartLimit)
        self.label_34 = QtWidgets.QLabel(self.countStatisticsBarChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_19.addWidget(self.label_34)
        spacerItem3 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem3)
        self.repaintCountStatisticsBarChartButton = QtWidgets.QPushButton(self.countStatisticsBarChartTab)
        self.repaintCountStatisticsBarChartButton.setObjectName("repaintCountStatisticsBarChartButton")
        self.horizontalLayout_19.addWidget(self.repaintCountStatisticsBarChartButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem4)
        self.countStatisticsBarChartTabLayout.addLayout(self.horizontalLayout_19)
        self.tabWidget_8.addTab(self.countStatisticsBarChartTab, "")
        self.countStatisticsPieChartTab = QtWidgets.QWidget()
        self.countStatisticsPieChartTab.setObjectName("countStatisticsPieChartTab")
        self.countStatisticsPieChartTabLayout = QtWidgets.QVBoxLayout(self.countStatisticsPieChartTab)
        self.countStatisticsPieChartTabLayout.setContentsMargins(0, 0, 0, 0)
        self.countStatisticsPieChartTabLayout.setSpacing(0)
        self.countStatisticsPieChartTabLayout.setObjectName("countStatisticsPieChartTabLayout")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(-1, 30, -1, 50)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem5)
        self.label_35 = QtWidgets.QLabel(self.countStatisticsPieChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_20.addWidget(self.label_35)
        self.countStatisticsPieChartLimit = QtWidgets.QLineEdit(self.countStatisticsPieChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countStatisticsPieChartLimit.sizePolicy().hasHeightForWidth())
        self.countStatisticsPieChartLimit.setSizePolicy(sizePolicy)
        self.countStatisticsPieChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.countStatisticsPieChartLimit.setObjectName("countStatisticsPieChartLimit")
        self.horizontalLayout_20.addWidget(self.countStatisticsPieChartLimit)
        self.label_36 = QtWidgets.QLabel(self.countStatisticsPieChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_20.addWidget(self.label_36)
        spacerItem6 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem6)
        self.repaintCountStatisticsPieChartButton = QtWidgets.QPushButton(self.countStatisticsPieChartTab)
        self.repaintCountStatisticsPieChartButton.setObjectName("repaintCountStatisticsPieChartButton")
        self.horizontalLayout_20.addWidget(self.repaintCountStatisticsPieChartButton)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem7)
        self.countStatisticsPieChartTabLayout.addLayout(self.horizontalLayout_20)
        self.tabWidget_8.addTab(self.countStatisticsPieChartTab, "")
        self.verticalLayout_3.addWidget(self.tabWidget_8)
        self.stackedWidget.addWidget(self.countStatisticsPage)
        self.oddEvenPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oddEvenPage.sizePolicy().hasHeightForWidth())
        self.oddEvenPage.setSizePolicy(sizePolicy)
        self.oddEvenPage.setObjectName("oddEvenPage")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.oddEvenPage)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tabWidget_9 = QtWidgets.QTabWidget(self.oddEvenPage)
        self.tabWidget_9.setObjectName("tabWidget_9")
        self.oddEvenTableTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oddEvenTableTab.sizePolicy().hasHeightForWidth())
        self.oddEvenTableTab.setSizePolicy(sizePolicy)
        self.oddEvenTableTab.setObjectName("oddEvenTableTab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.oddEvenTableTab)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.oddEvenTable = QtWidgets.QTableWidget(self.oddEvenTableTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oddEvenTable.sizePolicy().hasHeightForWidth())
        self.oddEvenTable.setSizePolicy(sizePolicy)
        self.oddEvenTable.setObjectName("oddEvenTable")
        self.oddEvenTable.setColumnCount(0)
        self.oddEvenTable.setRowCount(0)
        self.verticalLayout_8.addWidget(self.oddEvenTable)
        spacerItem8 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem8)
        self.exportOddEven = QtWidgets.QPushButton(self.oddEvenTableTab)
        self.exportOddEven.setObjectName("exportOddEven")
        self.verticalLayout_8.addWidget(self.exportOddEven)
        self.tabWidget_9.addTab(self.oddEvenTableTab, "")
        self.oddEvenBarChartTab = QtWidgets.QWidget()
        self.oddEvenBarChartTab.setObjectName("oddEvenBarChartTab")
        self.oddEvenBarChartTabLayout = QtWidgets.QVBoxLayout(self.oddEvenBarChartTab)
        self.oddEvenBarChartTabLayout.setContentsMargins(0, 0, 0, 0)
        self.oddEvenBarChartTabLayout.setSpacing(0)
        self.oddEvenBarChartTabLayout.setObjectName("oddEvenBarChartTabLayout")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_26.setContentsMargins(-1, 30, -1, 50)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem9)
        self.label_45 = QtWidgets.QLabel(self.oddEvenBarChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_26.addWidget(self.label_45)
        self.oddEvenBarChartLimit = QtWidgets.QLineEdit(self.oddEvenBarChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oddEvenBarChartLimit.sizePolicy().hasHeightForWidth())
        self.oddEvenBarChartLimit.setSizePolicy(sizePolicy)
        self.oddEvenBarChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.oddEvenBarChartLimit.setObjectName("oddEvenBarChartLimit")
        self.horizontalLayout_26.addWidget(self.oddEvenBarChartLimit)
        self.label_46 = QtWidgets.QLabel(self.oddEvenBarChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_46.sizePolicy().hasHeightForWidth())
        self.label_46.setSizePolicy(sizePolicy)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_26.addWidget(self.label_46)
        spacerItem10 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem10)
        self.repaintOddEvenBarChartButton = QtWidgets.QPushButton(self.oddEvenBarChartTab)
        self.repaintOddEvenBarChartButton.setObjectName("repaintOddEvenBarChartButton")
        self.horizontalLayout_26.addWidget(self.repaintOddEvenBarChartButton)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem11)
        self.oddEvenBarChartTabLayout.addLayout(self.horizontalLayout_26)
        self.tabWidget_9.addTab(self.oddEvenBarChartTab, "")
        self.oddEvenPieChartTab = QtWidgets.QWidget()
        self.oddEvenPieChartTab.setObjectName("oddEvenPieChartTab")
        self.oddEvenPieChartTabLayout = QtWidgets.QVBoxLayout(self.oddEvenPieChartTab)
        self.oddEvenPieChartTabLayout.setContentsMargins(0, 0, 0, 0)
        self.oddEvenPieChartTabLayout.setSpacing(0)
        self.oddEvenPieChartTabLayout.setObjectName("oddEvenPieChartTabLayout")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setContentsMargins(-1, 30, -1, 50)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem12)
        self.label_47 = QtWidgets.QLabel(self.oddEvenPieChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_47.sizePolicy().hasHeightForWidth())
        self.label_47.setSizePolicy(sizePolicy)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_27.addWidget(self.label_47)
        self.oddEvenPieChartLimit = QtWidgets.QLineEdit(self.oddEvenPieChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oddEvenPieChartLimit.sizePolicy().hasHeightForWidth())
        self.oddEvenPieChartLimit.setSizePolicy(sizePolicy)
        self.oddEvenPieChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.oddEvenPieChartLimit.setObjectName("oddEvenPieChartLimit")
        self.horizontalLayout_27.addWidget(self.oddEvenPieChartLimit)
        self.label_48 = QtWidgets.QLabel(self.oddEvenPieChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_48.sizePolicy().hasHeightForWidth())
        self.label_48.setSizePolicy(sizePolicy)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_27.addWidget(self.label_48)
        spacerItem13 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem13)
        self.repaintOddEvenPieChartButton = QtWidgets.QPushButton(self.oddEvenPieChartTab)
        self.repaintOddEvenPieChartButton.setObjectName("repaintOddEvenPieChartButton")
        self.horizontalLayout_27.addWidget(self.repaintOddEvenPieChartButton)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem14)
        self.oddEvenPieChartTabLayout.addLayout(self.horizontalLayout_27)
        self.tabWidget_9.addTab(self.oddEvenPieChartTab, "")
        self.verticalLayout_9.addWidget(self.tabWidget_9)
        self.stackedWidget.addWidget(self.oddEvenPage)
        self.bigSmallPage = QtWidgets.QWidget()
        self.bigSmallPage.setObjectName("bigSmallPage")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.bigSmallPage)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.tabWidget_10 = QtWidgets.QTabWidget(self.bigSmallPage)
        self.tabWidget_10.setObjectName("tabWidget_10")
        self.bigSmallTableTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bigSmallTableTab.sizePolicy().hasHeightForWidth())
        self.bigSmallTableTab.setSizePolicy(sizePolicy)
        self.bigSmallTableTab.setObjectName("bigSmallTableTab")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.bigSmallTableTab)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.bigSmallTable = QtWidgets.QTableWidget(self.bigSmallTableTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bigSmallTable.sizePolicy().hasHeightForWidth())
        self.bigSmallTable.setSizePolicy(sizePolicy)
        self.bigSmallTable.setObjectName("bigSmallTable")
        self.bigSmallTable.setColumnCount(0)
        self.bigSmallTable.setRowCount(0)
        self.verticalLayout_11.addWidget(self.bigSmallTable)
        spacerItem15 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_11.addItem(spacerItem15)
        self.exportBigSmall = QtWidgets.QPushButton(self.bigSmallTableTab)
        self.exportBigSmall.setObjectName("exportBigSmall")
        self.verticalLayout_11.addWidget(self.exportBigSmall)
        self.tabWidget_10.addTab(self.bigSmallTableTab, "")
        self.bigSmallBarChartTab = QtWidgets.QWidget()
        self.bigSmallBarChartTab.setObjectName("bigSmallBarChartTab")
        self.bigSmallBarChartTabLayout = QtWidgets.QVBoxLayout(self.bigSmallBarChartTab)
        self.bigSmallBarChartTabLayout.setContentsMargins(0, 0, 0, 0)
        self.bigSmallBarChartTabLayout.setSpacing(0)
        self.bigSmallBarChartTabLayout.setObjectName("bigSmallBarChartTabLayout")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_30.setContentsMargins(-1, 30, -1, 50)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem16)
        self.label_53 = QtWidgets.QLabel(self.bigSmallBarChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_53.sizePolicy().hasHeightForWidth())
        self.label_53.setSizePolicy(sizePolicy)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_30.addWidget(self.label_53)
        self.bigSmallBarChartLimit = QtWidgets.QLineEdit(self.bigSmallBarChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bigSmallBarChartLimit.sizePolicy().hasHeightForWidth())
        self.bigSmallBarChartLimit.setSizePolicy(sizePolicy)
        self.bigSmallBarChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.bigSmallBarChartLimit.setObjectName("bigSmallBarChartLimit")
        self.horizontalLayout_30.addWidget(self.bigSmallBarChartLimit)
        self.label_54 = QtWidgets.QLabel(self.bigSmallBarChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_54.sizePolicy().hasHeightForWidth())
        self.label_54.setSizePolicy(sizePolicy)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_30.addWidget(self.label_54)
        spacerItem17 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem17)
        self.repaintBigSmallBarChartButton = QtWidgets.QPushButton(self.bigSmallBarChartTab)
        self.repaintBigSmallBarChartButton.setObjectName("repaintBigSmallBarChartButton")
        self.horizontalLayout_30.addWidget(self.repaintBigSmallBarChartButton)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem18)
        self.bigSmallBarChartTabLayout.addLayout(self.horizontalLayout_30)
        self.tabWidget_10.addTab(self.bigSmallBarChartTab, "")
        self.bigSmallPieChartTab = QtWidgets.QWidget()
        self.bigSmallPieChartTab.setObjectName("bigSmallPieChartTab")
        self.bigSmallPieChartTabLayout = QtWidgets.QVBoxLayout(self.bigSmallPieChartTab)
        self.bigSmallPieChartTabLayout.setContentsMargins(0, 0, 0, 0)
        self.bigSmallPieChartTabLayout.setSpacing(0)
        self.bigSmallPieChartTabLayout.setObjectName("bigSmallPieChartTabLayout")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setContentsMargins(-1, 30, -1, 50)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem19)
        self.label_55 = QtWidgets.QLabel(self.bigSmallPieChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_55.sizePolicy().hasHeightForWidth())
        self.label_55.setSizePolicy(sizePolicy)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_31.addWidget(self.label_55)
        self.bigSmallPieChartLimit = QtWidgets.QLineEdit(self.bigSmallPieChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bigSmallPieChartLimit.sizePolicy().hasHeightForWidth())
        self.bigSmallPieChartLimit.setSizePolicy(sizePolicy)
        self.bigSmallPieChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.bigSmallPieChartLimit.setObjectName("bigSmallPieChartLimit")
        self.horizontalLayout_31.addWidget(self.bigSmallPieChartLimit)
        self.label_56 = QtWidgets.QLabel(self.bigSmallPieChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_56.sizePolicy().hasHeightForWidth())
        self.label_56.setSizePolicy(sizePolicy)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_31.addWidget(self.label_56)
        spacerItem20 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem20)
        self.repaintBigSmallPieChartButton = QtWidgets.QPushButton(self.bigSmallPieChartTab)
        self.repaintBigSmallPieChartButton.setObjectName("repaintBigSmallPieChartButton")
        self.horizontalLayout_31.addWidget(self.repaintBigSmallPieChartButton)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem21)
        self.bigSmallPieChartTabLayout.addLayout(self.horizontalLayout_31)
        self.tabWidget_10.addTab(self.bigSmallPieChartTab, "")
        self.verticalLayout_12.addWidget(self.tabWidget_10)
        self.stackedWidget.addWidget(self.bigSmallPage)
        self.yinYangPage = QtWidgets.QWidget()
        self.yinYangPage.setObjectName("yinYangPage")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.yinYangPage)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.tabWidget_11 = QtWidgets.QTabWidget(self.yinYangPage)
        self.tabWidget_11.setObjectName("tabWidget_11")
        self.yinYangTableTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yinYangTableTab.sizePolicy().hasHeightForWidth())
        self.yinYangTableTab.setSizePolicy(sizePolicy)
        self.yinYangTableTab.setObjectName("yinYangTableTab")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.yinYangTableTab)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.yinYangTable = QtWidgets.QTableWidget(self.yinYangTableTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yinYangTable.sizePolicy().hasHeightForWidth())
        self.yinYangTable.setSizePolicy(sizePolicy)
        self.yinYangTable.setObjectName("yinYangTable")
        self.yinYangTable.setColumnCount(0)
        self.yinYangTable.setRowCount(0)
        self.verticalLayout_14.addWidget(self.yinYangTable)
        spacerItem22 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_14.addItem(spacerItem22)
        self.exportYinYang = QtWidgets.QPushButton(self.yinYangTableTab)
        self.exportYinYang.setObjectName("exportYinYang")
        self.verticalLayout_14.addWidget(self.exportYinYang)
        self.tabWidget_11.addTab(self.yinYangTableTab, "")
        self.yinYangBarChartTab = QtWidgets.QWidget()
        self.yinYangBarChartTab.setObjectName("yinYangBarChartTab")
        self.yinYangBarChartTabLayout = QtWidgets.QVBoxLayout(self.yinYangBarChartTab)
        self.yinYangBarChartTabLayout.setContentsMargins(0, 0, 0, 0)
        self.yinYangBarChartTabLayout.setSpacing(0)
        self.yinYangBarChartTabLayout.setObjectName("yinYangBarChartTabLayout")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_34.setContentsMargins(-1, 30, -1, 50)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem23)
        self.label_61 = QtWidgets.QLabel(self.yinYangBarChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_61.sizePolicy().hasHeightForWidth())
        self.label_61.setSizePolicy(sizePolicy)
        self.label_61.setObjectName("label_61")
        self.horizontalLayout_34.addWidget(self.label_61)
        self.yinYangBarChartLimit = QtWidgets.QLineEdit(self.yinYangBarChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yinYangBarChartLimit.sizePolicy().hasHeightForWidth())
        self.yinYangBarChartLimit.setSizePolicy(sizePolicy)
        self.yinYangBarChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.yinYangBarChartLimit.setObjectName("yinYangBarChartLimit")
        self.horizontalLayout_34.addWidget(self.yinYangBarChartLimit)
        self.label_62 = QtWidgets.QLabel(self.yinYangBarChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_62.sizePolicy().hasHeightForWidth())
        self.label_62.setSizePolicy(sizePolicy)
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_34.addWidget(self.label_62)
        spacerItem24 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem24)
        self.repaintYinYangBarChartButton = QtWidgets.QPushButton(self.yinYangBarChartTab)
        self.repaintYinYangBarChartButton.setObjectName("repaintYinYangBarChartButton")
        self.horizontalLayout_34.addWidget(self.repaintYinYangBarChartButton)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem25)
        self.yinYangBarChartTabLayout.addLayout(self.horizontalLayout_34)
        self.tabWidget_11.addTab(self.yinYangBarChartTab, "")
        self.yinYangPieChartTab = QtWidgets.QWidget()
        self.yinYangPieChartTab.setObjectName("yinYangPieChartTab")
        self.yinYangPieChartTabLayout = QtWidgets.QVBoxLayout(self.yinYangPieChartTab)
        self.yinYangPieChartTabLayout.setContentsMargins(0, 0, 0, 0)
        self.yinYangPieChartTabLayout.setSpacing(0)
        self.yinYangPieChartTabLayout.setObjectName("yinYangPieChartTabLayout")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setContentsMargins(-1, 30, -1, 50)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem26)
        self.label_63 = QtWidgets.QLabel(self.yinYangPieChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_63.sizePolicy().hasHeightForWidth())
        self.label_63.setSizePolicy(sizePolicy)
        self.label_63.setObjectName("label_63")
        self.horizontalLayout_35.addWidget(self.label_63)
        self.yinYangPieChartLimit = QtWidgets.QLineEdit(self.yinYangPieChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yinYangPieChartLimit.sizePolicy().hasHeightForWidth())
        self.yinYangPieChartLimit.setSizePolicy(sizePolicy)
        self.yinYangPieChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.yinYangPieChartLimit.setObjectName("yinYangPieChartLimit")
        self.horizontalLayout_35.addWidget(self.yinYangPieChartLimit)
        self.label_64 = QtWidgets.QLabel(self.yinYangPieChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_64.sizePolicy().hasHeightForWidth())
        self.label_64.setSizePolicy(sizePolicy)
        self.label_64.setObjectName("label_64")
        self.horizontalLayout_35.addWidget(self.label_64)
        spacerItem27 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem27)
        self.repaintYinYangPieChartButton = QtWidgets.QPushButton(self.yinYangPieChartTab)
        self.repaintYinYangPieChartButton.setObjectName("repaintYinYangPieChartButton")
        self.horizontalLayout_35.addWidget(self.repaintYinYangPieChartButton)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem28)
        self.yinYangPieChartTabLayout.addLayout(self.horizontalLayout_35)
        self.tabWidget_11.addTab(self.yinYangPieChartTab, "")
        self.verticalLayout_15.addWidget(self.tabWidget_11)
        self.stackedWidget.addWidget(self.yinYangPage)
        self.primeCompositePage = QtWidgets.QWidget()
        self.primeCompositePage.setObjectName("primeCompositePage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.primeCompositePage)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget_12 = QtWidgets.QTabWidget(self.primeCompositePage)
        self.tabWidget_12.setObjectName("tabWidget_12")
        self.primeCompositeTableTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.primeCompositeTableTab.sizePolicy().hasHeightForWidth())
        self.primeCompositeTableTab.setSizePolicy(sizePolicy)
        self.primeCompositeTableTab.setObjectName("primeCompositeTableTab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.primeCompositeTableTab)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.primeCompositeTable = QtWidgets.QTableWidget(self.primeCompositeTableTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.primeCompositeTable.sizePolicy().hasHeightForWidth())
        self.primeCompositeTable.setSizePolicy(sizePolicy)
        self.primeCompositeTable.setObjectName("primeCompositeTable")
        self.primeCompositeTable.setColumnCount(0)
        self.primeCompositeTable.setRowCount(0)
        self.verticalLayout_10.addWidget(self.primeCompositeTable)
        spacerItem29 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_10.addItem(spacerItem29)
        self.exportPrimeComposite = QtWidgets.QPushButton(self.primeCompositeTableTab)
        self.exportPrimeComposite.setObjectName("exportPrimeComposite")
        self.verticalLayout_10.addWidget(self.exportPrimeComposite)
        self.tabWidget_12.addTab(self.primeCompositeTableTab, "")
        self.primeCompositeBarChartTab = QtWidgets.QWidget()
        self.primeCompositeBarChartTab.setObjectName("primeCompositeBarChartTab")
        self.primeCompositeBarChartTabLayout = QtWidgets.QVBoxLayout(self.primeCompositeBarChartTab)
        self.primeCompositeBarChartTabLayout.setContentsMargins(0, 0, 0, 0)
        self.primeCompositeBarChartTabLayout.setSpacing(0)
        self.primeCompositeBarChartTabLayout.setObjectName("primeCompositeBarChartTabLayout")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_28.setContentsMargins(-1, 30, -1, 50)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem30)
        self.label_49 = QtWidgets.QLabel(self.primeCompositeBarChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_49.sizePolicy().hasHeightForWidth())
        self.label_49.setSizePolicy(sizePolicy)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_28.addWidget(self.label_49)
        self.primeCompositeBarChartLimit = QtWidgets.QLineEdit(self.primeCompositeBarChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.primeCompositeBarChartLimit.sizePolicy().hasHeightForWidth())
        self.primeCompositeBarChartLimit.setSizePolicy(sizePolicy)
        self.primeCompositeBarChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.primeCompositeBarChartLimit.setObjectName("primeCompositeBarChartLimit")
        self.horizontalLayout_28.addWidget(self.primeCompositeBarChartLimit)
        self.label_50 = QtWidgets.QLabel(self.primeCompositeBarChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_50.sizePolicy().hasHeightForWidth())
        self.label_50.setSizePolicy(sizePolicy)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_28.addWidget(self.label_50)
        spacerItem31 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem31)
        self.repaintPrimeCompositeBarChartButton = QtWidgets.QPushButton(self.primeCompositeBarChartTab)
        self.repaintPrimeCompositeBarChartButton.setObjectName("repaintPrimeCompositeBarChartButton")
        self.horizontalLayout_28.addWidget(self.repaintPrimeCompositeBarChartButton)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem32)
        self.primeCompositeBarChartTabLayout.addLayout(self.horizontalLayout_28)
        self.tabWidget_12.addTab(self.primeCompositeBarChartTab, "")
        self.primeCompositePieChartTab = QtWidgets.QWidget()
        self.primeCompositePieChartTab.setObjectName("primeCompositePieChartTab")
        self.primeCompositePieChartTabLayout = QtWidgets.QVBoxLayout(self.primeCompositePieChartTab)
        self.primeCompositePieChartTabLayout.setContentsMargins(0, 0, 0, 0)
        self.primeCompositePieChartTabLayout.setSpacing(0)
        self.primeCompositePieChartTabLayout.setObjectName("primeCompositePieChartTabLayout")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setContentsMargins(-1, 30, -1, 50)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem33)
        self.label_51 = QtWidgets.QLabel(self.primeCompositePieChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_51.sizePolicy().hasHeightForWidth())
        self.label_51.setSizePolicy(sizePolicy)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_29.addWidget(self.label_51)
        self.primeCompositePieChartLimit = QtWidgets.QLineEdit(self.primeCompositePieChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.primeCompositePieChartLimit.sizePolicy().hasHeightForWidth())
        self.primeCompositePieChartLimit.setSizePolicy(sizePolicy)
        self.primeCompositePieChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.primeCompositePieChartLimit.setObjectName("primeCompositePieChartLimit")
        self.horizontalLayout_29.addWidget(self.primeCompositePieChartLimit)
        self.label_52 = QtWidgets.QLabel(self.primeCompositePieChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_52.sizePolicy().hasHeightForWidth())
        self.label_52.setSizePolicy(sizePolicy)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_29.addWidget(self.label_52)
        spacerItem34 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem34)
        self.repaintPrimeCompositePieChartButton = QtWidgets.QPushButton(self.primeCompositePieChartTab)
        self.repaintPrimeCompositePieChartButton.setObjectName("repaintPrimeCompositePieChartButton")
        self.horizontalLayout_29.addWidget(self.repaintPrimeCompositePieChartButton)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem35)
        self.primeCompositePieChartTabLayout.addLayout(self.horizontalLayout_29)
        self.tabWidget_12.addTab(self.primeCompositePieChartTab, "")
        self.verticalLayout_5.addWidget(self.tabWidget_12)
        self.stackedWidget.addWidget(self.primeCompositePage)
        self.calcSumPage = QtWidgets.QWidget()
        self.calcSumPage.setObjectName("calcSumPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.calcSumPage)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget_13 = QtWidgets.QTabWidget(self.calcSumPage)
        self.tabWidget_13.setObjectName("tabWidget_13")
        self.calcSumTableTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calcSumTableTab.sizePolicy().hasHeightForWidth())
        self.calcSumTableTab.setSizePolicy(sizePolicy)
        self.calcSumTableTab.setObjectName("calcSumTableTab")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.calcSumTableTab)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.calcSumTable = QtWidgets.QTableWidget(self.calcSumTableTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calcSumTable.sizePolicy().hasHeightForWidth())
        self.calcSumTable.setSizePolicy(sizePolicy)
        self.calcSumTable.setObjectName("calcSumTable")
        self.calcSumTable.setColumnCount(0)
        self.calcSumTable.setRowCount(0)
        self.verticalLayout_13.addWidget(self.calcSumTable)
        spacerItem36 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_13.addItem(spacerItem36)
        self.exportCalcSum = QtWidgets.QPushButton(self.calcSumTableTab)
        self.exportCalcSum.setObjectName("exportCalcSum")
        self.verticalLayout_13.addWidget(self.exportCalcSum)
        self.tabWidget_13.addTab(self.calcSumTableTab, "")
        self.calcSumBarChartTab = QtWidgets.QWidget()
        self.calcSumBarChartTab.setObjectName("calcSumBarChartTab")
        self.calcSumBarChartTabLayout = QtWidgets.QVBoxLayout(self.calcSumBarChartTab)
        self.calcSumBarChartTabLayout.setContentsMargins(0, 0, 0, 0)
        self.calcSumBarChartTabLayout.setSpacing(0)
        self.calcSumBarChartTabLayout.setObjectName("calcSumBarChartTabLayout")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_32.setContentsMargins(-1, 30, -1, 50)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem37)
        self.label_57 = QtWidgets.QLabel(self.calcSumBarChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_57.sizePolicy().hasHeightForWidth())
        self.label_57.setSizePolicy(sizePolicy)
        self.label_57.setObjectName("label_57")
        self.horizontalLayout_32.addWidget(self.label_57)
        self.calcSumBarChartLimit = QtWidgets.QLineEdit(self.calcSumBarChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calcSumBarChartLimit.sizePolicy().hasHeightForWidth())
        self.calcSumBarChartLimit.setSizePolicy(sizePolicy)
        self.calcSumBarChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.calcSumBarChartLimit.setObjectName("calcSumBarChartLimit")
        self.horizontalLayout_32.addWidget(self.calcSumBarChartLimit)
        self.label_58 = QtWidgets.QLabel(self.calcSumBarChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_58.sizePolicy().hasHeightForWidth())
        self.label_58.setSizePolicy(sizePolicy)
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_32.addWidget(self.label_58)
        spacerItem38 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem38)
        self.repaintCalcSumBarChartButton = QtWidgets.QPushButton(self.calcSumBarChartTab)
        self.repaintCalcSumBarChartButton.setObjectName("repaintCalcSumBarChartButton")
        self.horizontalLayout_32.addWidget(self.repaintCalcSumBarChartButton)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem39)
        self.calcSumBarChartTabLayout.addLayout(self.horizontalLayout_32)
        self.tabWidget_13.addTab(self.calcSumBarChartTab, "")
        self.calcSumPieChartTab = QtWidgets.QWidget()
        self.calcSumPieChartTab.setObjectName("calcSumPieChartTab")
        self.calcSumPieChartTabLayout = QtWidgets.QVBoxLayout(self.calcSumPieChartTab)
        self.calcSumPieChartTabLayout.setContentsMargins(0, 0, 0, 0)
        self.calcSumPieChartTabLayout.setSpacing(0)
        self.calcSumPieChartTabLayout.setObjectName("calcSumPieChartTabLayout")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setContentsMargins(-1, 30, -1, 50)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem40)
        self.label_59 = QtWidgets.QLabel(self.calcSumPieChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_59.sizePolicy().hasHeightForWidth())
        self.label_59.setSizePolicy(sizePolicy)
        self.label_59.setObjectName("label_59")
        self.horizontalLayout_33.addWidget(self.label_59)
        self.calcSumPieChartLimit = QtWidgets.QLineEdit(self.calcSumPieChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calcSumPieChartLimit.sizePolicy().hasHeightForWidth())
        self.calcSumPieChartLimit.setSizePolicy(sizePolicy)
        self.calcSumPieChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.calcSumPieChartLimit.setObjectName("calcSumPieChartLimit")
        self.horizontalLayout_33.addWidget(self.calcSumPieChartLimit)
        self.label_60 = QtWidgets.QLabel(self.calcSumPieChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_60.sizePolicy().hasHeightForWidth())
        self.label_60.setSizePolicy(sizePolicy)
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_33.addWidget(self.label_60)
        spacerItem41 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem41)
        self.repaintCalcSumPieChartButton = QtWidgets.QPushButton(self.calcSumPieChartTab)
        self.repaintCalcSumPieChartButton.setObjectName("repaintCalcSumPieChartButton")
        self.horizontalLayout_33.addWidget(self.repaintCalcSumPieChartButton)
        spacerItem42 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem42)
        self.calcSumPieChartTabLayout.addLayout(self.horizontalLayout_33)
        self.tabWidget_13.addTab(self.calcSumPieChartTab, "")
        self.verticalLayout_6.addWidget(self.tabWidget_13)
        self.stackedWidget.addWidget(self.calcSumPage)
        self.calc012Page = QtWidgets.QWidget()
        self.calc012Page.setObjectName("calc012Page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.calc012Page)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tabWidget_14 = QtWidgets.QTabWidget(self.calc012Page)
        self.tabWidget_14.setObjectName("tabWidget_14")
        self.calc012TableTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calc012TableTab.sizePolicy().hasHeightForWidth())
        self.calc012TableTab.setSizePolicy(sizePolicy)
        self.calc012TableTab.setObjectName("calc012TableTab")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.calc012TableTab)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.calc012Table = QtWidgets.QTableWidget(self.calc012TableTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calc012Table.sizePolicy().hasHeightForWidth())
        self.calc012Table.setSizePolicy(sizePolicy)
        self.calc012Table.setObjectName("calc012Table")
        self.calc012Table.setColumnCount(0)
        self.calc012Table.setRowCount(0)
        self.verticalLayout_16.addWidget(self.calc012Table)
        spacerItem43 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_16.addItem(spacerItem43)
        self.exportCalc012 = QtWidgets.QPushButton(self.calc012TableTab)
        self.exportCalc012.setObjectName("exportCalc012")
        self.verticalLayout_16.addWidget(self.exportCalc012)
        self.tabWidget_14.addTab(self.calc012TableTab, "")
        self.calc012BarChartTab = QtWidgets.QWidget()
        self.calc012BarChartTab.setObjectName("calc012BarChartTab")
        self.calc012BarChartTabLayout = QtWidgets.QVBoxLayout(self.calc012BarChartTab)
        self.calc012BarChartTabLayout.setContentsMargins(0, 0, 0, 0)
        self.calc012BarChartTabLayout.setSpacing(0)
        self.calc012BarChartTabLayout.setObjectName("calc012BarChartTabLayout")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_36.setContentsMargins(-1, 30, -1, 50)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        spacerItem44 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem44)
        self.label_65 = QtWidgets.QLabel(self.calc012BarChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_65.sizePolicy().hasHeightForWidth())
        self.label_65.setSizePolicy(sizePolicy)
        self.label_65.setObjectName("label_65")
        self.horizontalLayout_36.addWidget(self.label_65)
        self.calc012BarChartLimit = QtWidgets.QLineEdit(self.calc012BarChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calc012BarChartLimit.sizePolicy().hasHeightForWidth())
        self.calc012BarChartLimit.setSizePolicy(sizePolicy)
        self.calc012BarChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.calc012BarChartLimit.setObjectName("calc012BarChartLimit")
        self.horizontalLayout_36.addWidget(self.calc012BarChartLimit)
        self.label_66 = QtWidgets.QLabel(self.calc012BarChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_66.sizePolicy().hasHeightForWidth())
        self.label_66.setSizePolicy(sizePolicy)
        self.label_66.setObjectName("label_66")
        self.horizontalLayout_36.addWidget(self.label_66)
        spacerItem45 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem45)
        self.repaintCalc012BarChartButton = QtWidgets.QPushButton(self.calc012BarChartTab)
        self.repaintCalc012BarChartButton.setObjectName("repaintCalc012BarChartButton")
        self.horizontalLayout_36.addWidget(self.repaintCalc012BarChartButton)
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem46)
        self.calc012BarChartTabLayout.addLayout(self.horizontalLayout_36)
        self.tabWidget_14.addTab(self.calc012BarChartTab, "")
        self.calc012PieChartTab = QtWidgets.QWidget()
        self.calc012PieChartTab.setObjectName("calc012PieChartTab")
        self.calc012PieChartTabLayout = QtWidgets.QVBoxLayout(self.calc012PieChartTab)
        self.calc012PieChartTabLayout.setContentsMargins(0, 0, 0, 0)
        self.calc012PieChartTabLayout.setSpacing(0)
        self.calc012PieChartTabLayout.setObjectName("calc012PieChartTabLayout")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setContentsMargins(-1, 30, -1, 50)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        spacerItem47 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem47)
        self.label_67 = QtWidgets.QLabel(self.calc012PieChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_67.sizePolicy().hasHeightForWidth())
        self.label_67.setSizePolicy(sizePolicy)
        self.label_67.setObjectName("label_67")
        self.horizontalLayout_37.addWidget(self.label_67)
        self.calc012PieChartLimit = QtWidgets.QLineEdit(self.calc012PieChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calc012PieChartLimit.sizePolicy().hasHeightForWidth())
        self.calc012PieChartLimit.setSizePolicy(sizePolicy)
        self.calc012PieChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.calc012PieChartLimit.setObjectName("calc012PieChartLimit")
        self.horizontalLayout_37.addWidget(self.calc012PieChartLimit)
        self.label_68 = QtWidgets.QLabel(self.calc012PieChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_68.sizePolicy().hasHeightForWidth())
        self.label_68.setSizePolicy(sizePolicy)
        self.label_68.setObjectName("label_68")
        self.horizontalLayout_37.addWidget(self.label_68)
        spacerItem48 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem48)
        self.repaintCalc012PieChartButton = QtWidgets.QPushButton(self.calc012PieChartTab)
        self.repaintCalc012PieChartButton.setObjectName("repaintCalc012PieChartButton")
        self.horizontalLayout_37.addWidget(self.repaintCalc012PieChartButton)
        spacerItem49 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem49)
        self.calc012PieChartTabLayout.addLayout(self.horizontalLayout_37)
        self.tabWidget_14.addTab(self.calc012PieChartTab, "")
        self.verticalLayout_7.addWidget(self.tabWidget_14)
        self.stackedWidget.addWidget(self.calc012Page)
        self.calcSpanPage = QtWidgets.QWidget()
        self.calcSpanPage.setObjectName("calcSpanPage")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.calcSpanPage)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.tabWidget_15 = QtWidgets.QTabWidget(self.calcSpanPage)
        self.tabWidget_15.setObjectName("tabWidget_15")
        self.calcSpanTableTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calcSpanTableTab.sizePolicy().hasHeightForWidth())
        self.calcSpanTableTab.setSizePolicy(sizePolicy)
        self.calcSpanTableTab.setObjectName("calcSpanTableTab")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.calcSpanTableTab)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.calcSpanTable = QtWidgets.QTableWidget(self.calcSpanTableTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calcSpanTable.sizePolicy().hasHeightForWidth())
        self.calcSpanTable.setSizePolicy(sizePolicy)
        self.calcSpanTable.setObjectName("calcSpanTable")
        self.calcSpanTable.setColumnCount(0)
        self.calcSpanTable.setRowCount(0)
        self.verticalLayout_17.addWidget(self.calcSpanTable)
        spacerItem50 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_17.addItem(spacerItem50)
        self.exportCalcSpan = QtWidgets.QPushButton(self.calcSpanTableTab)
        self.exportCalcSpan.setObjectName("exportCalcSpan")
        self.verticalLayout_17.addWidget(self.exportCalcSpan)
        self.tabWidget_15.addTab(self.calcSpanTableTab, "")
        self.calcSpanBarChartTab = QtWidgets.QWidget()
        self.calcSpanBarChartTab.setObjectName("calcSpanBarChartTab")
        self.calcSpanBarChartTabLayout = QtWidgets.QVBoxLayout(self.calcSpanBarChartTab)
        self.calcSpanBarChartTabLayout.setContentsMargins(0, 0, 0, 0)
        self.calcSpanBarChartTabLayout.setSpacing(0)
        self.calcSpanBarChartTabLayout.setObjectName("calcSpanBarChartTabLayout")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_38.setContentsMargins(-1, 30, -1, 50)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        spacerItem51 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem51)
        self.label_69 = QtWidgets.QLabel(self.calcSpanBarChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_69.sizePolicy().hasHeightForWidth())
        self.label_69.setSizePolicy(sizePolicy)
        self.label_69.setObjectName("label_69")
        self.horizontalLayout_38.addWidget(self.label_69)
        self.calcSpanBarChartLimit = QtWidgets.QLineEdit(self.calcSpanBarChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calcSpanBarChartLimit.sizePolicy().hasHeightForWidth())
        self.calcSpanBarChartLimit.setSizePolicy(sizePolicy)
        self.calcSpanBarChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.calcSpanBarChartLimit.setObjectName("calcSpanBarChartLimit")
        self.horizontalLayout_38.addWidget(self.calcSpanBarChartLimit)
        self.label_70 = QtWidgets.QLabel(self.calcSpanBarChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_70.sizePolicy().hasHeightForWidth())
        self.label_70.setSizePolicy(sizePolicy)
        self.label_70.setObjectName("label_70")
        self.horizontalLayout_38.addWidget(self.label_70)
        spacerItem52 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem52)
        self.repaintCalcSpanBarChartButton = QtWidgets.QPushButton(self.calcSpanBarChartTab)
        self.repaintCalcSpanBarChartButton.setObjectName("repaintCalcSpanBarChartButton")
        self.horizontalLayout_38.addWidget(self.repaintCalcSpanBarChartButton)
        spacerItem53 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem53)
        self.calcSpanBarChartTabLayout.addLayout(self.horizontalLayout_38)
        self.tabWidget_15.addTab(self.calcSpanBarChartTab, "")
        self.calcSpanPieChartTab = QtWidgets.QWidget()
        self.calcSpanPieChartTab.setObjectName("calcSpanPieChartTab")
        self.calcSpanPieChartTabLayout = QtWidgets.QVBoxLayout(self.calcSpanPieChartTab)
        self.calcSpanPieChartTabLayout.setContentsMargins(0, 0, 0, 0)
        self.calcSpanPieChartTabLayout.setSpacing(0)
        self.calcSpanPieChartTabLayout.setObjectName("calcSpanPieChartTabLayout")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setContentsMargins(-1, 30, -1, 50)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        spacerItem54 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem54)
        self.label_71 = QtWidgets.QLabel(self.calcSpanPieChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_71.sizePolicy().hasHeightForWidth())
        self.label_71.setSizePolicy(sizePolicy)
        self.label_71.setObjectName("label_71")
        self.horizontalLayout_39.addWidget(self.label_71)
        self.calcSpanPieChartLimit = QtWidgets.QLineEdit(self.calcSpanPieChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calcSpanPieChartLimit.sizePolicy().hasHeightForWidth())
        self.calcSpanPieChartLimit.setSizePolicy(sizePolicy)
        self.calcSpanPieChartLimit.setMaximumSize(QtCore.QSize(45, 16777215))
        self.calcSpanPieChartLimit.setObjectName("calcSpanPieChartLimit")
        self.horizontalLayout_39.addWidget(self.calcSpanPieChartLimit)
        self.label_72 = QtWidgets.QLabel(self.calcSpanPieChartTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_72.sizePolicy().hasHeightForWidth())
        self.label_72.setSizePolicy(sizePolicy)
        self.label_72.setObjectName("label_72")
        self.horizontalLayout_39.addWidget(self.label_72)
        spacerItem55 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem55)
        self.repaintCalcSpanPieChartButton = QtWidgets.QPushButton(self.calcSpanPieChartTab)
        self.repaintCalcSpanPieChartButton.setObjectName("repaintCalcSpanPieChartButton")
        self.horizontalLayout_39.addWidget(self.repaintCalcSpanPieChartButton)
        spacerItem56 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem56)
        self.calcSpanPieChartTabLayout.addLayout(self.horizontalLayout_39)
        self.tabWidget_15.addTab(self.calcSpanPieChartTab, "")
        self.verticalLayout_18.addWidget(self.tabWidget_15)
        self.stackedWidget.addWidget(self.calcSpanPage)
        self.horizontalLayout_12.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.rightFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget_8.setCurrentIndex(0)
        self.tabWidget_9.setCurrentIndex(0)
        self.tabWidget_10.setCurrentIndex(0)
        self.tabWidget_11.setCurrentIndex(0)
        self.tabWidget_12.setCurrentIndex(0)
        self.tabWidget_13.setCurrentIndex(0)
        self.tabWidget_14.setCurrentIndex(0)
        self.tabWidget_15.setCurrentIndex(0)
        self.menuList.currentRowChanged['int'].connect(self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        __sortingEnabled = self.menuList.isSortingEnabled()
        self.menuList.setSortingEnabled(False)
        item = self.menuList.item(0)
        item.setText(_translate("MainWindow", "数据总览"))
        item = self.menuList.item(1)
        item.setText(_translate("MainWindow", "号码出现次数"))
        item = self.menuList.item(2)
        item.setText(_translate("MainWindow", "次数统计"))
        item = self.menuList.item(3)
        item.setText(_translate("MainWindow", "奇偶"))
        item = self.menuList.item(4)
        item.setText(_translate("MainWindow", "大小"))
        item = self.menuList.item(5)
        item.setText(_translate("MainWindow", "阴阳"))
        item = self.menuList.item(6)
        item.setText(_translate("MainWindow", "质合"))
        item = self.menuList.item(7)
        item.setText(_translate("MainWindow", "和值"))
        item = self.menuList.item(8)
        item.setText(_translate("MainWindow", "012路"))
        item = self.menuList.item(9)
        item.setText(_translate("MainWindow", "跨度"))
        self.menuList.setSortingEnabled(__sortingEnabled)
        self.exportAllData.setText(_translate("MainWindow", "导出为 excel"))
        self.perNumberCountTable.setSortingEnabled(True)
        self.exportPerNumberCount.setText(_translate("MainWindow", "导出为 excel"))
        self.exportCountStatistics.setText(_translate("MainWindow", "导出为 excel"))
        self.tabWidget_8.setTabText(self.tabWidget_8.indexOf(self.countStatisticsTableTab), _translate("MainWindow", "表格"))
        self.label_33.setText(_translate("MainWindow", "最近  "))
        self.label_34.setText(_translate("MainWindow", "  期"))
        self.repaintCountStatisticsBarChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_8.setTabText(self.tabWidget_8.indexOf(self.countStatisticsBarChartTab), _translate("MainWindow", "柱形图"))
        self.label_35.setText(_translate("MainWindow", "最近  "))
        self.label_36.setText(_translate("MainWindow", "  期"))
        self.repaintCountStatisticsPieChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_8.setTabText(self.tabWidget_8.indexOf(self.countStatisticsPieChartTab), _translate("MainWindow", "扇形图"))
        self.exportOddEven.setText(_translate("MainWindow", "导出为 excel"))
        self.tabWidget_9.setTabText(self.tabWidget_9.indexOf(self.oddEvenTableTab), _translate("MainWindow", "表格"))
        self.label_45.setText(_translate("MainWindow", "最近  "))
        self.label_46.setText(_translate("MainWindow", "  期"))
        self.repaintOddEvenBarChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_9.setTabText(self.tabWidget_9.indexOf(self.oddEvenBarChartTab), _translate("MainWindow", "柱形图"))
        self.label_47.setText(_translate("MainWindow", "最近  "))
        self.label_48.setText(_translate("MainWindow", "  期"))
        self.repaintOddEvenPieChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_9.setTabText(self.tabWidget_9.indexOf(self.oddEvenPieChartTab), _translate("MainWindow", "扇形图"))
        self.exportBigSmall.setText(_translate("MainWindow", "导出为 excel"))
        self.tabWidget_10.setTabText(self.tabWidget_10.indexOf(self.bigSmallTableTab), _translate("MainWindow", "表格"))
        self.label_53.setText(_translate("MainWindow", "最近  "))
        self.label_54.setText(_translate("MainWindow", "  期"))
        self.repaintBigSmallBarChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_10.setTabText(self.tabWidget_10.indexOf(self.bigSmallBarChartTab), _translate("MainWindow", "柱形图"))
        self.label_55.setText(_translate("MainWindow", "最近  "))
        self.label_56.setText(_translate("MainWindow", "  期"))
        self.repaintBigSmallPieChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_10.setTabText(self.tabWidget_10.indexOf(self.bigSmallPieChartTab), _translate("MainWindow", "扇形图"))
        self.exportYinYang.setText(_translate("MainWindow", "导出为 excel"))
        self.tabWidget_11.setTabText(self.tabWidget_11.indexOf(self.yinYangTableTab), _translate("MainWindow", "表格"))
        self.label_61.setText(_translate("MainWindow", "最近  "))
        self.label_62.setText(_translate("MainWindow", "  期"))
        self.repaintYinYangBarChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_11.setTabText(self.tabWidget_11.indexOf(self.yinYangBarChartTab), _translate("MainWindow", "柱形图"))
        self.label_63.setText(_translate("MainWindow", "最近  "))
        self.label_64.setText(_translate("MainWindow", "  期"))
        self.repaintYinYangPieChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_11.setTabText(self.tabWidget_11.indexOf(self.yinYangPieChartTab), _translate("MainWindow", "扇形图"))
        self.exportPrimeComposite.setText(_translate("MainWindow", "导出为 excel"))
        self.tabWidget_12.setTabText(self.tabWidget_12.indexOf(self.primeCompositeTableTab), _translate("MainWindow", "表格"))
        self.label_49.setText(_translate("MainWindow", "最近  "))
        self.label_50.setText(_translate("MainWindow", "  期"))
        self.repaintPrimeCompositeBarChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_12.setTabText(self.tabWidget_12.indexOf(self.primeCompositeBarChartTab), _translate("MainWindow", "柱形图"))
        self.label_51.setText(_translate("MainWindow", "最近  "))
        self.label_52.setText(_translate("MainWindow", "  期"))
        self.repaintPrimeCompositePieChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_12.setTabText(self.tabWidget_12.indexOf(self.primeCompositePieChartTab), _translate("MainWindow", "扇形图"))
        self.exportCalcSum.setText(_translate("MainWindow", "导出为 excel"))
        self.tabWidget_13.setTabText(self.tabWidget_13.indexOf(self.calcSumTableTab), _translate("MainWindow", "表格"))
        self.label_57.setText(_translate("MainWindow", "最近  "))
        self.label_58.setText(_translate("MainWindow", "  期"))
        self.repaintCalcSumBarChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_13.setTabText(self.tabWidget_13.indexOf(self.calcSumBarChartTab), _translate("MainWindow", "柱形图"))
        self.label_59.setText(_translate("MainWindow", "最近  "))
        self.label_60.setText(_translate("MainWindow", "  期"))
        self.repaintCalcSumPieChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_13.setTabText(self.tabWidget_13.indexOf(self.calcSumPieChartTab), _translate("MainWindow", "扇形图"))
        self.exportCalc012.setText(_translate("MainWindow", "导出为 excel"))
        self.tabWidget_14.setTabText(self.tabWidget_14.indexOf(self.calc012TableTab), _translate("MainWindow", "表格"))
        self.label_65.setText(_translate("MainWindow", "最近  "))
        self.label_66.setText(_translate("MainWindow", "  期"))
        self.repaintCalc012BarChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_14.setTabText(self.tabWidget_14.indexOf(self.calc012BarChartTab), _translate("MainWindow", "柱形图"))
        self.label_67.setText(_translate("MainWindow", "最近  "))
        self.label_68.setText(_translate("MainWindow", "  期"))
        self.repaintCalc012PieChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_14.setTabText(self.tabWidget_14.indexOf(self.calc012PieChartTab), _translate("MainWindow", "扇形图"))
        self.exportCalcSpan.setText(_translate("MainWindow", "导出为 excel"))
        self.tabWidget_15.setTabText(self.tabWidget_15.indexOf(self.calcSpanTableTab), _translate("MainWindow", "表格"))
        self.label_69.setText(_translate("MainWindow", "最近  "))
        self.label_70.setText(_translate("MainWindow", "  期"))
        self.repaintCalcSpanBarChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_15.setTabText(self.tabWidget_15.indexOf(self.calcSpanBarChartTab), _translate("MainWindow", "柱形图"))
        self.label_71.setText(_translate("MainWindow", "最近  "))
        self.label_72.setText(_translate("MainWindow", "  期"))
        self.repaintCalcSpanPieChartButton.setText(_translate("MainWindow", "重绘"))
        self.tabWidget_15.setTabText(self.tabWidget_15.indexOf(self.calcSpanPieChartTab), _translate("MainWindow", "扇形图"))
